# Generated by Django 3.0.7 on 2020-06-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fen', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('moves', models.TextField(default='')),
                ('pgn_meta', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.TextField(default=None)),
            ],
        ),
    ]
