# Generated by Django 3.0.7 on 2020-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_auto_20200629_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgn',
            old_name='src',
            new_name='black',
        ),
        migrations.RemoveField(
            model_name='chessboard',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='chessboard',
            name='pgn_meta',
        ),
        migrations.AddField(
            model_name='pgn',
            name='date',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pgn',
            name='event',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pgn',
            name='moves',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pgn',
            name='result',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pgn',
            name='round',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pgn',
            name='site',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='pgn',
            name='white',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
