# Generated by Django 3.0.7 on 2020-06-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0003_auto_20200630_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboard',
            name='black',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chessboard',
            name='white',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='black',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='date',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='event',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='moves',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='result',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='round',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='site',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pgn',
            name='white',
            field=models.TextField(default=None, null=True),
        ),
    ]
