# Generated by Django 3.0.7 on 2020-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0004_auto_20200630_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgn',
            name='moves',
            field=models.TextField(default=''),
        ),
    ]
